version: 2

project_name: ccbit

builds:
  - main: ./cmd/ccbit
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - name_template: "ccbit_{{ .Os }}_{{ .Arch }}"
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  use: github
